name: Build docker collabora image

on:
  workflow_run:
    workflows: ["Repo Sync"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-amd64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [
          {name: 'aio-collabora', context: './Containers/collabora', file: './Containers/collabora/Dockerfile'},
        ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to ghcr.io
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ${{ matrix.container.context }}
          file: ${{ matrix.container.file }}
          platforms: linux/amd64
          no-cache: true
          push: true
          tags: ghcr.io/lenoregilbert/${{ matrix.container.name }}:develop

  build-arm64:
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        container: [
          {name: 'aio-collabora', context: './Containers/collabora', file: './Containers/collabora/Dockerfile'},
        ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5
      - name: Login to ghcr.io
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image and push to ghcr.io
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: ${{ matrix.container.context }}
          file: ${{ matrix.container.file }}
          platforms: linux/arm64
          no-cache: true
          push: true
          tags: ghcr.io/lenoregilbert/${{ matrix.container.name }}:develop-arm64
