name: Promote to beta

on:
  workflow_dispatch:

jobs:
  promote_to_latest:
    runs-on: ubuntu-latest
    name: Promote from develop to beta 
    
    strategy:
      fail-fast: false
      matrix:
        name: [
          'aio-alpine',
          'aio-apache',
          'aio-borgbackup',
          'aio-collabora',
          'aio-domaincheck',
          'all-in-one',
          'aio-nextcloud',
          'aio-notify-push',
          'aio-postgresql',
          'aio-redis',
          'aio-talk',
          'aio-watchtower',
          'aio-clamav',
          'aio-onlyoffice',
          'aio-imaginary',
          'aio-talk-recording',
          'aio-fulltextsearch',
          'aio-docker-socket-proxy',
          'aio-whiteboard']

    steps:
    - name: Login to ghcr.io
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Promote images from develop to beta (create multiarch) on ghcr.io
      run: |
        set -x
        AIO_NAME=${{ matrix.name }}
        set +x
        
        # create multiarch image
        docker buildx imagetools create --tag ghcr.io/lenoregilbert/$AIO_NAME\:beta ghcr.io/lenoregilbert/$AIO_NAME\:develop ghcr.io/lenoregilbert/$AIO_NAME\:develop-arm64

        # arm64
        docker buildx imagetools create --tag ghcr.io/lenoregilbert/$AIO_NAME\:beta-arm64 ghcr.io/lenoregilbert/$AIO_NAME\:develop ghcr.io/lenoregilbert/$AIO_NAME\:develop-arm64

    - name: Login to DockerHub
      if: matrix.name == 'all-in-one'
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Promote images from develop to beta (create multiarch) on docker hub
      if: matrix.name == 'all-in-one'
      run: |
        # create multiarch image
        docker buildx imagetools create --tag nextcloud/all-in-one\:beta ghcr.io/lenoregilbert/all-in-one\:develop ghcr.io/lenoregilbert/all-in-one\:develop-arm64
        
        # arm64
        docker buildx imagetools create --tag nextcloud/all-in-one\:beta-arm64 ghcr.io/lenoregilbert/all-in-one\:develop ghcr.io/lenoregilbert/all-in-one\:develop-arm64
