name: Publish to AWS

on:
  workflow_dispatch:

jobs:
  publish_to_digitalocean:
    runs-on: ubuntu-latest
    name: Publish image to AWS

    steps:
    - uses: actions/checkout@v5
    - name: Install Packer
      run: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        sudo apt-get update && sudo apt-get install packer
        packer --version
    - name: Create Image
      run: |
        cd ./.build/aws
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        set -x
        packer init aws-ubuntu.pkr.hcl
        packer validate aws-ubuntu.pkr.hcl
        packer build aws-ubuntu.pkr.hcl
        set +x
