name: Shellcheck

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: Check Shell
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Run Shellcheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
      with:
        check_together: 'yes'
      env:
        SHELLCHECK_OPTS: --shell bash
